# Generated by Django 3.0.8 on 2023-10-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0006_education_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedDocument',
        ),
    ]
