# Generated by Django 3.0.8 on 2023-10-21 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0007_delete_saveddocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='file',
            new_name='my_file',
        ),
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.AddField(
            model_name='education',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='education',
            name='status',
            field=models.CharField(choices=[('junior', 'junior'), ('average', 'average'), ('senior', 'senior'), ('experienced', 'experienced')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
