# Generated by Django 3.0.8 on 2023-10-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0008_auto_20231021_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
