# Generated by Django 3.0.8 on 2023-10-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0009_auto_20231021_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
