# Generated by Django 3.0.8 on 2023-10-21 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0010_auto_20231021_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='profile_image',
        ),
    ]
