# Generated by Django 3.0.8 on 2023-10-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0012_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='my_doc',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
